packages:
  - .
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  '@vaadin/vaadin-usage-statistics': true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
